### ISSUE TITLE
Support easy helm installation

### ISSUE THREAD

**Issue by zhouzhuojie** [openflagr/flagr#197]

**Comment by adnaangr** [comment]
Hi, Would it be ok if I pick this up or Maybe you have a secret helm file already :)

**Comment by travisghansen** [comment]
I've created a crude start that I'll be using internally..happy to hand the files over if you want them. Supports mysql/postgres and sqlite.

**Comment by rishi-pratap** [comment]
Do we have helm installation available for flagr yet ?

**Comment by travisghansen** [comment]
I have a crude chart I created..

**Comment by rishi-pratap** [comment]
Thats great... can you please share it?

**Comment by travisghansen** [comment]
Try this: https://github.com/travisghansen/scratch/raw/master/files/flagr-0.1.0.tgz

**Comment by aayush-allen** [comment]
Does anyone have updated helm chart ?

**Comment by ericbsantana** [comment]
Hello @nothing0012 @zhouzhuojie @aayush-harwani 

I have created a simple Helm Chart for Flagr - it is easy to kickstart and has some docs. The repository is available [here](https://github.com/ericbsantana/flagr-helm-chart).

```bash
helm repo add flagr https://ericbsantana.github.io/flagr-helm-chart
helm install flagr flagr/flagr --devel
```

It has support to envs through `extraEnvs` value so it is easy to enable Prometheus metrics, change database configuration and also supports `valueFrom` to use secrets that have database connection strings in it. As everything is controlled through environment variables, this simple setup should be enough for certain production environments.

The [values.yaml](https://github.com/ericbsantana/flagr-helm-chart/blob/main/charts/flagr/values.yaml) and [README.md](https://github.com/ericbsantana/flagr-helm-chart/blob/main/charts/flagr/README.md) inside the `charts/flagr` folder provides more information about it.

Hope this is helpful! Let me know if you have any questions or feedback.
