### ISSUE TITLE
[feat] add notification channel for flag updates

### ISSUE THREAD

**Issue by zhouzhuojie** [openflagr/flagr#214]
Teams need more visibility into how and when flags are updated. For example, Email or Slack notifications can be good channels.

Not sure if this feature is a good addon to the current Flagr setup. Maybe we can build it in Flagr, maybe we can expose Flagr webhooks and let other applications implement it.

**Comment by crberube** [comment]
The webhook approach sounds interesting because that would enable flexibility for many different use cases / notification channels.
