### ISSUE TITLE
Add integration tests for all the swagger generated SDKs

### ISSUE THREAD

**Issue by zhouzhuojie** [openflagr/flagr#241]
As we are constantly upgrading Flagr server, the client SDKs may experience unexpected changes from the server side. The integration tests should better include these SDKs instead of just simple CURL tests.

Specifically, we want to cover
- https://github.com/checkr/jsflagr
- https://github.com/checkr/rbflagr
- https://github.com/checkr/pyflagr
- https://github.com/checkr/goflagr

**Comment by riteshmodi** [comment]
Hi @zhouzhuojie, I would like to work on this issue.
