### ISSUE TITLE
[feat] Add enrichment option to get entity context detail based on entity ID

### ISSUE THREAD

**Issue by dileepbapat** [openflagr/flagr#291]
In microservice environment, flagr might be used from many different services with entity ID. However, if there is an entity resolving/ enrichment  layer it would reduce need to get metadata from each of those consumers.

Let me know if this is in line with the roadmap.

**Comment by zhouzhuojie** [comment]
This is great idea, and I think it's domain-specific and better be done by the application itself instead of Flagr. Flagr is entity agnostic, and that's why entity context is passed in not derived from within Flagr. Let me know what do you think?

**Comment by dileepbapat** [comment]
Since whitelisting and jwt available I assume this meant to be also
consumed by UI/js however expectation to pass all entity context from UI
might be against "expose only necessary information to external world"

I am thinking of domain agnostic way to enrich the context. A sort of
optional resolver in middle. If enabled call out configured rest API and
merge with entity context.

Thoughts?
