### ISSUE TITLE
Bug: can't setup distribution for 100+ variants

### ISSUE THREAD

**Issue by 4n70w4** [openflagr/flagr#307]
I sucesfully add 280 variants for flag. And will grow up to 10 000+ in the future.

Via UI I can't set float distribution percent for variant.

Via API I get error `cannot unmarshal number 0.1 into Go struct field Distribution.percent of type int64`

As a result, I can add more than 100 variants, but I can only distribute only no more 100 variants.

**Comment by zhouzhuojie** [comment]
This is a very interesting use case I didn't think of before, can you elaborate on how are you going to use 100+ variants?

Flagr's model uses static `1000` buckets for deterministic hashing, that's why we didn't use float distribution.  

https://checkr.github.io/flagr/#/flagr_overview - "Rollout"

**Comment by 4n70w4** [comment]
@zhouzhuojie marketing cases.... an variant may be a promocode for product, service, category, brand, etc.
