### ISSUE TITLE
Bug: only first segment distributed if few segments have identical constraints

### ISSUE THREAD

**Issue by 4n70w4** [openflagr/flagr#308]
I try solve my problem https://github.com/checkr/flagr/issues/307 with use few segments. But failure.

I sucesfully add few segments with identical constraints (empty constraints).

![image](https://user-images.githubusercontent.com/38257723/69495418-e28efa80-0ed7-11ea-9a00-4e5b99c2c7cd.png)

But in evaluate distributed only first segment. I try different values for rollout %, but in all cases one bahaviour.

**Comment by zhouzhuojie** [comment]
![image](https://user-images.githubusercontent.com/658840/69562579-54148a80-0f64-11ea-832a-cabd29c9b4bf.png)

https://checkr.github.io/flagr/#/flagr_use_cases

That's expected behavior, segments order is important, and if entities fall into a segment, we stop going to the next segment.

**Comment by 4n70w4** [comment]
@zhouzhuojie thanks, I didn't see this item in the documentation. So this will not solve my problem (
