### ISSUE TITLE
[Feature Request] Optionally strip EntityContext from evaluation responses

### ISSUE THREAD

**Issue by dseabolt** [openflagr/flagr#312]
My intended use case is to make a single evaluation at session start when we have an expected loading period using batch evaluation. This works well, but the size of the responses are very large because the entity context is repeated for each flag, and it doesn't provide any additional information outside of debugging. 

I understand that in the case of evaluating for several entities you'd need the entity ID to resolve which evaluation is for which entity, but it seems that the context, (which is also the most data heavy part of the context), could be optionally stripped to optimize the size of the response.

I do need to provide the context initially for constraints in my segments during evaluation, but I don't care about them in my response. 

Does this seem reasonable?

**Comment by zhouzhuojie** [comment]
Sounds good! I think we can systematically handle the response size problem, especially for batch evaluation.

A few things to note:
- Make sure the entity context is still logged into recorder for analytics purpose
- Have finer granularity to control which fields in the evaluation result can be nulled/removed.

PRs are always welcome!
