### ISSUE TITLE
[feat] Share segments across multiple flags

### ISSUE THREAD

**Issue by dcramer** [openflagr/flagr#346]
It'd be nice to be able to create some complex segments once. For example, say you have this somewhat common scenario:

- Alpha design partners begin testing feature A
- Alpha design partners begin testing feature B
- feature A graduates to include beta customers
- feature B graduates to include beta customers

In each of those you'd have to define "alpha" and "beta" in your app (defeating the purpose of the features system), or you'd have to copy paste what may become complex constraint logic between the two.

**Comment by dcramer** [comment]
One bonus of supporting this is it makes the system much more usable, as it means product owners can understand pre-defined segments vs having to look at what 'context' is available in payloads.

**Comment by zhouzhuojie** [comment]
Yes, however segment has attributes like "rollout percent" and "distribution" that's usually not sharable across flags.

I'm think you are likely referring to a concept called "Audience" (or constraints set, or cohorts), that a set of global constraints that can be shared across flags. And yes, that totally works, and it's a really nice feature.

**Comment by dcramer** [comment]
Yeah constraints (or set of constraints) is more what I'm thinking. We'd define things like:

- Beta Users
- Early Adopters
- Product Team X
- Staff

If we could simply define those elsewhere then use them in segments (as a constraint) that might be an easy enough solution? I could take a stab at an implementation if we can agree on the high level design.
