### ISSUE TITLE
[feat] Client Side Caching

### ISSUE THREAD

**Issue by Cull-Methi** [openflagr/flagr#350]
For the purposes of reliability we're trying to think of some ways that we can make our services withstand flagr being down (network link cut, bad deployment, whatever might cause it to go down).

Internally we've discussed a couple options, namely a sidecar process, nginx cache, and client-side caching. We think the client-side cache is the way to go:

- Sidecar adds a lot of overhead and makes it difficult to use some services out there that run containers for you (namely AWS ECS, but others as well) when you don't have control over the host running your container
- Nginx cache is only good for evaluations that have already occurred - if you try to evaluate against a new entity that evaluation would be a cache miss and (if the backend were down) fail

Client side caching obviously makes things a lot more difficult - currently the clients are all generated code, so they would need to be edited to have that caching available, but we think it's the best option (per the Possible Solution below)

## Possible Solution

Our thoughts are to implement caching in the client in this way:

Clients will no longer call the Evaluation endpoint directly - instead, the clients will do a GET on the flag and its variants, cache that locally for a configurable amount of time, and do the evaluation locally, utilizing a cache (LRU probably?) to keep some of the highest traffic evaluations. This appears to be similar to #298 

For example:

My `go` service will do the same thing it does today:

```go
// Create our evaluation context
        eval_ctx := goflagr.EvalContext{
                FlagID:        flagId,
        }

        // Ask the flagr backend to evaluate 
        // our context and tell us what color to show
        result, _, err := apiClient.
                EvaluationApi.
                PostEvaluation(nil, eval_ctx)
```

But instead of `PostEvaluation` doing its usual REST call to the flagr backend, it would instead do something like the following pseudo code:

```
func PostEvaluation(eval_ctx){
  if isInCache(eval_ctx.flag) and flagCacheIsValid(eval_ctx.flag){

   //localEvaluation() has its own cache of evaluations against a flag - want to limit it so as not to be a memory hog
    return localEvaluation(eval_ctx)

  }
  flag := getFlagFromBackend(eval_ctx.flag.id)
  //getFlagFromBackend would handle the case where the backend is down and return the old flag
  // If the flag isn't cached already will behave the same way it does today - fail


  addToCache(flag)
  return localEvaluation(eval_ctx)
}
```

Where `localEvaluation` is more or less a copy/paste job of EvalFlag from `eval.go`

## Context

Mostly this is to guard against the case where _something_ happens and the flagr backend is unreachable for whatever reason, but it also has a number of performance benefits for flagr on the backend. Doing this with reasonable cache lifetimes could allow the backend application to serve many more clients with the same set of resources - it could take thousands of RPS to one or two requests per minute for a busy application evaluating against the same flag.

Additionally, since it's all local it will increase the memory footprint of the client, but only as much as the application uses, as it acts as its own pass-through cache. Because running code locally can be  orders of magnitude faster than going across the network (especially if the flagr backend lives in another zone that goes over the WAN) this should allow users of the client a much better level of performance for their code, at the cost of a slightly higher memory footprint

**Comment by zhouzhuojie** [comment]
Thanks for the issue. Actually, I think flagr natively support the sidecar deployment. For example, below is a doc string for  DBDriver and DBConnectionStr:

``` 
   /**
    DBDriver and DBConnectionStr define how we can write and read flags data.
    For databases, flagr supports sqlite3, mysql and postgres.
    For read-only evaluation, flagr supports file and http.

    Examples:

    FLAGR_DB_DBDRIVER     FLAGR_DB_DBCONNECTIONSTR
    =================     ===============================================================
    "sqlite3"             "/tmp/file.db"
    "sqlite3"             ":memory:"
    "mysql"               "root:@tcp(127.0.0.1:18100)/flagr?parseTime=true"
    "postgres"            "postgres://user:password@host:5432/flagr?sslmode=disable"

    "json_file"           "/tmp/flags.json"                    # (it automatically sets EvalOnlyMode=true)
    "json_http"           "https://example.com/flags.json"     # (it automatically sets EvalOnlyMode=true)

    */
```

You can deploy two types of flagrs: 
- `control plane` - that connects to FLAGR_DB_DBDRIVER with a database, and you can do your normal CRUD, UI, flags management; and
- `data plane` - that connects to json_http with FLAGR_DB_DBCONNECTIONSTR points to the `control plane`'s export_json endpoint. (https://checkr.github.io/flagr/api_docs/#operation/getExportEvalCacheJSON) Note that this the `data plane` will periodically sync with this endpoint to refresh its in-memory cache, and you can just use it as the sidecar into your deployments.

**Comment by Cull-Methi** [comment]
While I like the sidecar deployment, my infrastructure team is actively trying to avoid the sidecar architecture when possible. Thus, we'd like to be able to do the caching in the client itself. I'm curious if you'd be open to putting that into the `goflagr` library, since it would force a change to the library as it'd no longer be pure generated code

**Comment by zhouzhuojie** [comment]
Sorry I might miss something from my previous comment, and yes, sidecar has its own maintenance cost, especially one may need to be careful when redeploy the sidecars. If you are running on k8s, the deployment allows you to deploy multiple containers, which might be a good place to bundle the flagr deployment with your normal applications; that being said, it's an extra step for your infra and application team to maintain.

For client side caching, as I mentioned in #298, we need to answer a few questions:
- how to sync
- how to do cache invalidation

If you are using go client, it's possible to directly import flagr server side code with the eval_cache refresh logic - it's equivalent of running flagr server embedded.

**Comment by zhouzhuojie** [comment]
> While I like the sidecar deployment, my infrastructure team is actively trying to avoid the sidecar architecture when possible. Thus, we'd like to be able to do the caching in the client itself. I'm curious if you'd be open to putting that into the `goflagr` library, since it would force a change to the library as it'd no longer be pure generated code

Yes, definitely open to have changes in `goflagr`; Also, please make sure the newly generated code won't affect normal code.

**Comment by zhouzhuojie** [comment]
I'm also thinking of investing in webassembly and compile the whole `data plane` into its own wasm bytes (including its flags syncing logic and evaluation logic), and it can be applied to other client side languages.

**Comment by RussellLuo** [comment]
Hi guys, I have just developed a Caddy v2 extension named [flagr](https://github.com/RussellLuo/caddy-ext/tree/master/flagr) a few days ago, to apply Feature Flags by leveraging Flagr. The implementation of `Local Evaluator` happened to be exactly the same as described here https://github.com/checkr/flagr/issues/350#issuecomment-610664779.

Cheers 🍺 😄
