### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by rsahoo752055** [openflagr/flagr#384]
Is there any TLS 1.2 or 1.3 support available for flagr?
If yes, how to enable TLS 1.2 or 1.3.

**Comment by brasilikum** [comment]
Hey @rsahoo752055,

As far as I can see, Flagr "supports" TLS as in nothing is preventing you from using it, but it does not "terminate" it, meaning you will need to have some kind of proxy to terminate the TLS.

We do it on Heroku, but you could also use the free Cloudflare service or use servers like NGIX or caddy(this one is really straight forward)

**Comment by zhouzhuojie** [comment]
Flagr was designed to be hosted internally, and usually people expose flagr via api gateway / reverse proxy / kubernetes ingresses and at that level you can terminate the TLS. 

That said, I think we can also look into support TLS natively. PRs are welcome! One can start with the following places:
 
- https://github.com/checkr/flagr/blob/master/swagger_gen/restapi/server.go#L229
