### ISSUE TITLE
Colour coded tags in Flagr UI.

### ISSUE THREAD

**Issue by SaxJ** [openflagr/flagr#438]
Hello. This is my first contribution to this project, and I thought I'll post a feature request here, and see if there is any interest in this idea before I go opening a PR. :)
## Description
Different tags have different colours in the Flagr UI. This would be purely a Flagr UI change.

## Why
A small quality of life improvement. Different tags colours allow a user to more easily see what flags have what tags when scanning through the tag list.
![Screenshot_2021-04-19 Flagr](https://user-images.githubusercontent.com/1689439/115189212-b69d9600-a118-11eb-8476-e49974d8761a.png)
![Screenshot_2021-04-19 Flagr(1)](https://user-images.githubusercontent.com/1689439/115189213-b7cec300-a118-11eb-96bd-272dc9b013ac.png)

**Comment by zhouzhuojie** [comment]
Nice! That's awesome! Btw, how do you generate the color? Is it like a hash of the tag so that the same tag always gets the same color?

**Comment by SaxJ** [comment]
Thank you :)
Yep, just a hash of the tag value to get a hue between (0, 360), then from that get a CSS `hsla` string. I've implemented it as a small helper method that the vue component calls.
