### ISSUE TITLE
Integrating elastic apm to flagr go docker image

### ISSUE THREAD

**Issue by gkkishan** [openflagr/flagr#452]
Hi - We are evaluating t to use flagr as the feature flagging tool in our organization. We want to integrate elastic APM to the flagr application which is build in go language.
Elastic APM: https://www.elastic.co/guide/en/apm/agent/go/current/index.html

We are using the docker image hosted by the flagr in docker repository. Do you guys have any documentation how to integrate this to flagr?

**Comment by Cull-Methi** [comment]
Flagr uses Negroni. Based on this github issue, it appears that APM doesn't support negroni natively but could be made to do so: https://github.com/elastic/apm-agent-go/issues/665
