### ISSUE TITLE
Whitelist based on HTTP verb

### ISSUE THREAD

**Issue by fredvollmer** [openflagr/flagr#462]
## Expected Behavior
It would be great if it was possible to whitelist a path only for certain HTTP verbs. For example, we would like to make `GET /api/v1/flags` publicly available but still require authentication to `POST` or `PUT` to `/api/v1/flags`.

## Current Behavior
Currently, whitelisting is based solely on path. There is no way to allow only `GET` access to a path.

Is there any way to achieve this currently? Is there any interest in a PR addressing it if not?

**Comment by marceloboeira** [comment]
I would highly recommend always using a reverse proxy/ingress to host things like flagr, so that you can have such controls on that layer.

**Comment by zhouzhuojie** [comment]
Second what @marceloboeira has suggested, usually a reverse proxy or api gateway works better in this case, and flagr can keep it simple and focus on the core features.

That said, it's also nice if the feature set can be extended to support sole hosting, e.g better authn and authz, SSL, and etc, but that will not be super high priority given that we are just reinventing what cloud or companies' internal infra offers.
