### ISSUE TITLE
Do you plan to release a new version?

### ISSUE THREAD

**Issue by juanancid** [openflagr/flagr#484]
The latest Flagr version is the `1.1.12` and it was released on 17 Sep 2020. Since then more than 30 changes have been committed to `master` but no new version has been released. Do you plan to release a new version? Do you still maintain the project?

**Comment by victordidenko** [comment]
As far as I understand, creators of flagr now maintains [community fork](https://github.com/openflagr/flagr), check [this comment](https://github.com/checkr/flagr/issues/447#issuecomment-894706777), but I may be wrong...

**Comment by juanancid** [comment]
Thank you very much @victordidenko. I read it and understood the same thing. I am planning to migrate to it, but wanted to double check if this project is still maintained.

**Comment by zhouzhuojie** [comment]
yes, just worked on the merge and repo transfer, and everything lives under openflagr org now.

**Comment by zhouzhuojie** [comment]
will prepare a release very soon

**Comment by zhouzhuojie** [comment]
https://github.com/openflagr/flagr/releases/tag/1.1.14 is live
