### ISSUE TITLE
Timeout: Flagr sometimes takes more than 500ms to respond

### ISSUE THREAD

**Issue by ejoo** [openflagr/flagr#491]
We have deployed Flagr in a K8S, and the service that talks to it constantly throws timeout errors. We have a timeout limit of 500ms, and Flagr takes more. Are there any recommendations for us to take a look into?

**Comment by marceloboeira** [comment]
Could you share your setup? (deployment.yaml). I have had used flagr with thousands of req/s and never had issues with response time since it is mostly loaded from memory, my experience has been under 10ms response time on p99

**Comment by ejoo** [comment]
Thanks for reply @marceloboeira. Never mind I think we've some issues with our codebase!
