### ISSUE TITLE
[feat] more detailed search options

### ISSUE THREAD

**Issue by cathteng** [openflagr/flagr#501]
Currently, the search bar on Flagr is limited to searching tags and descriptions. It would be nice if you could also search for specific constraints, i.e. searching for a specific constraint property name (`property:property-name`).

I ran into a case where I was modifying a method used to assign a value to a constraint property, and I had to manually check every single flag to see if that property was being used to make sure I wouldn't break anything. Adding this feature would save a lot of time in the future :)

**Comment by ofhope** [comment]
I'd be interested in working on this.

I assume we'd want to add syntactic sugar to the search in the format of `property-name:property-value`

**Comment by ofhope** [comment]
I have a working implementation. 
https://github.com/openflagr/flagr/compare/main...ofhope:flagr:refactor/client-search?expand=1

This allows me to search on a property of the Flag. 
<img width="588" alt="Screen Shot 2022-10-16 at 10 06 25 pm" src="https://user-images.githubusercontent.com/1826459/196032148-409c94a5-9abb-4ada-a187-c2d2b2b9478a.png">

This can only work on the properties loaded on the client.

If support for more properties is need one solution would be something like Riot (Go search library) and implementing search server side. This would allow searching on all properties across larger datasets. But is a more involved solution.

This fixes a few minor issues around string trimming. Previously spaces after commas were included in the match and failed to match. 

Working on some unit tests and documentation now. Setting up Jest for the project and this refactor 😬 

Some other considerations. 
* Might want to update UI packages as they're major versions behind and a few audit warnings
* Setting up `@vue/test-utils` to test some of the interface could be 👌🏽
