### ISSUE TITLE
"attempt to write a readonly database" in  ghcr.io/openflagr/flagr container

### ISSUE THREAD

**Issue by pdonovan-merit** [openflagr/flagr#503]
After creating an instance of ghcr.io/openflagr/flagr 1.1.14, attempting to create a new flag results in "attempt to write a readonly database"

Attempting write operations on the demo flag yields the same result.

## Expected Behavior

As with 1.1.13, we expect the UI to allow us to add and modify flags. The application/image does appear to work correctly with that version.

## Current Behavior

![image](https://user-images.githubusercontent.com/97061678/191118574-53a51af0-7016-41a4-8a96-a512d2478652.png)
This error is produced when we try to add a new flag.

## Steps to Reproduce (for bugs)

1. Create and start a new instance of ghcr.io/openflagr/flagr:latest (1.1.14)
2. Attempt to add a flag called "test"
3.
4.

## Your Environment

* Version used (`flagr version`):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by michaeljs1990** [comment]
This can be closed out. Guess github doesn't let you close out multiple tickets with one Closes or I just did it wrong.

**Comment by ajbogh** [comment]
@michaeljs1990 this might not have been published yet. Is that possible to do, or is there a workaround for this with 1.1.14?

**Comment by ajbogh** [comment]
@zhouzhuojie this build requires your approval for the heroku deployment. Can you do this? It's currently blocking people from using the docker instance since the sqlite database is readonly. I've tried several workarounds without luck.

https://github.com/openflagr/flagr/actions/runs/3205461667/jobs/5238010792
