### ISSUE TITLE
Support additional non sql database

### ISSUE THREAD

**Issue by dariolingotti** [openflagr/flagr#505]
I'd like to have this tool support AWS DynamoDB.

## Expected Behavior
They are cheaper than AWS RDS.

## Current Behavior
The application saves data in a relation database. HTTP env is read only.

## Possible Solution
Allow the application connect to a non sql database using their API in order to store the flags.

## Your Environment

* Version used (`flagr version`): 1.1
* Server type and version: AWS
* Operating System and version (`uname -a`): linux
* Link to your project: n/a

**Comment by marceloboeira** [comment]
It sounds interesting, but considering the way flagr is build (with [gorm](https://gorm.io)), it might be a significantly large project.
